In [2]:
#Question1
#This line generates a NumPy array named arr1 with a shape of (5, 3). 
#The elements in this array are randomly generated integers between 1 (inclusive) and 100 (exclusive)
arr1 = np.random.randint(1, 100, size=(5, 3))
print(arr1)

[[20 45 20]
 [43 19  6]
 [56 32 95]
 [13 77 20]
 [16 49 55]]


In [5]:
#Question2
# This line accesses the element at the 3rd row and 3rd column of the arr1 array 
number = arr1[2, 2]
print("The number in the third row, third column is:", number)

The number in the third row, third column is: 95


In [6]:
#Question3
#Slicing explained, 1: This is the starting index. It means you start the slice from the second element 
# ::2] -  It means you will take every second element starting from the starting index. In other words,
#you'll include every other element in the slice.
arr_slice = arr1[1::2]
print(arr_slice)

[[43 19  6]
 [13 77 20]]


In [11]:
#Question4
arr_slice[-1,-1] = 12345
print(arr_slice)
print("This changed the value of the last number in the arr1.")


[[   43    19     6]
 [   13    77 12345]]
This changed the value of the last number in the arr1.


In [16]:
#Question5
arr1 = np.random.randint(1, 100, size=(5, 3))

transpose_arr1 = arr1.transpose()
print(transpose_arr1)

[[ 2 84 50 56 15]
 [ 3 61 41 68 69]
 [38 72 60 30 96]]


In [15]:
#Question6
arr2 = np.random.choice(np.arange(1, 40, 2), size=(4, 5))
print(arr2)

[[ 7  7 23  5 29]
 [ 7 13  7 25  5]
 [19  9 21  7 27]
 [23 11  9 29  5]]


In [57]:
#Question7
arr1 = np.random.randint(1, 100, size=(5, 3))
arr2 = np.random.choice(np.arange(1, 40, 2), size=(4, 5))
transpose_arr2 = arr2.transpose()

arr_new = np.hstack((arr1, transpose_arr2))
print(arr_new)

[[96 10  8 17  3  7  9]
 [ 3  8  7  5 27 31 13]
 [23 91 27 39 37  5 17]
 [74 85 87 19 25  5 23]
 [ 6 12 17 39 19 21 27]]


In [59]:
#Question8
row_sum = np.sum(arr1, axis = 1)
print(arr1)

print("This is the sum of arr1 by row")
print(row_sum)

[[96 10  8]
 [ 3  8  7]
 [23 91 27]
 [74 85 87]
 [ 6 12 17]]
This is the sum of arr1 by row
[114  18 141 246  35]


In [33]:
#Question9
arr1 = np.random.randint(1, 100, size=(5, 3))
arr3 = np.random.randint(1, 100, size=(3, 3))
arr4 = np.random.randint(1, 100, size=(5, 3))

matrix_multiplication = np.dot(arr1, arr3)
element_multiplication = arr1 * arr4
print("This is the matrix multiplication")
print(matrix_multiplication)
print("This is the element multiplication")
print(element_multiplication)

This is the matrix multiplication
[[ 9657  9910 13460]
 [ 7527 10499 15668]
 [10075 10485 12999]
 [ 7704  9925 13418]
 [ 4993  4310  6569]]
This is the element multiplication
[[6030 4740 5670]
 [6586  946  195]
 [1998 2747 5185]
 [8036 2680  360]
 [ 176 2736  702]]


In [54]:
#Question10
oneD_arr = np.arange(1, 4)
print("This is a 1D array")
print(oneD_arr.shape)

twoD_arr = np.array([np.arange(1, 4), np.arange(1, 4), np.arange(1, 4)])
print("This is a 2D array")
print(twoD_arr.shape)

a1 = np.array([np.arange(1, 4), np.arange(1, 4), np.arange(1, 4)])
a2 = np.array([np.arange(1, 4), np.arange(1, 4), np.arange(1, 4)])
threeD_arr = np.array([a1, a2, a1])
print("This is a 3D array")
print(threeD_arr.shape)

This is a 1D array
(3,)
This is a 2D array
(3, 3)
This is a 3D array
(3, 3, 3)


THIS IS AN INDIVIDUAL ASSIGNMENT. YOU MAY NOT DISCUSS THIS ASSIGNMENT WITH ANYONE WITHIN OR OUTSIDE THE CLASS (except the instructor).
- DO not discuss your approaches or your code with colleagues. There are many ways to implement this assignment, and it is extremely easy to spot code that has been inspired by someone else’s code and to identify unauthorized collaborations.
- If you choose to utilize something you find online, cite that resource, but DO NOT share that resource with anyone else.
By submitting this assignment, you certify that no unauthorized assistance has been received or given in the completion of this work.


Ukari Overby
